spring:
  application:
    name: bookingservice
  profiles:
    active: dev  
  config:
      import: configserver:http://localhost:8888
  cloud:
    config:
      fail-fast: true    

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 9000