spring:
  config:
    import: configserver:http://localhost:8888
  application:
    name: propertyservice
  profiles:
    active: dev
  cloud:
    config:
      uri: http://localhost:8888
      fail-fast: true
server:
  port: 9093
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
