spring:
  application:
    name: paymentservice
  profiles:
    active: dev
  config:
    import: configserver:http://localhost:8888
  cloud:
    config:
      fail-fast: true
      
server:
  port: 9092
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

  
